#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions


case "$1" in
  configure)

    SERVICE_XPATH_NAME="docker"
    SERVICE_XPATH="/config/services/${SERVICE_XPATH_NAME}"

    #Setup initial OMV configuration
    if ! omv_config_exists "/config/services/docker"; then
      echo "Initialize configuration"
      omv_config_add_node "/config/services" "${SERVICE_XPATH_NAME}"
      omv_config_add_key "${SERVICE_XPATH}" "apiPort" "42005"
      omv_config_add_key "${SERVICE_XPATH}" "sharedfolderref" ""
      omv_config_add_key "${SERVICE_XPATH}" "enabled" "0"
      omv_config_add_key "${SERVICE_XPATH}" "dockermntent" ""
      omv_config_add_key "${SERVICE_XPATH}" "cwarn" "1"
    fi

    sed -i '/DOCKER_OPTS="$DOCKER_OPTS $OMVDOCKER_API $OMVDOCKER_IMAGE_PATH"/d' /etc/default/docker

    #Update systemd daemon and start the Docker service
    systemctl stop docker.socket
    systemctl stop docker
    systemctl daemon-reload
    systemctl start docker

    dpkg-trigger update-fixperms
    dpkg-trigger update-locale

    ;;

abort-upgrade|abort-remove|abort-deconfigure)
    ;;

*)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

#DEBHELPER#

exit 0
