#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

CONFIG="/config/services/docker"

case "$1" in
    remove)
        ;;

    purge)
        if [ -f /etc/default/docker ]; then
            DOCKERSERVICE=`ps aux | grep "/usr/bin/docker daemon" | grep -v grep | wc -l`
            if [ $DOCKERSERVICE -eq 1 ]; then
                DOCKERCONTAINERS=`docker ps -q | wc -l`
                if [ $DOCKERCONTAINERS -gt 0 ]; then
                    docker ps -q | xargs docker kill
                fi
                service docker stop
            fi
            sed -i '/### Do not change these lines\. They are added and updated by the OMV Docker GUI plugin\./,$d' /etc/default/docker
            service docker start
        fi

        if omv_config_exists $CONFIG; then
            echo "Deleting Configuration"
            omv_config_delete $CONFIG;
        fi

        if ! omv_config_exists $CONFIG; then
            echo "Configuration Deleted"
        fi
        ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

exit 0
