#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

CONFIG="/config/services/docker"

case "$1" in
  purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	
	  if [ -f /etc/default/docker ]; then
		service docker stop
		sed -i '/### Do not change these lines. They are added and updated by the OMV Docker GUI plugin./,$d' /etc/default/docker
		service docker start
	fi

    if omv_config_exists $CONFIG; then
      echo "Deleting Configuration"
      omv_config_delete $CONFIG;
    fi

    if ! omv_config_exists $CONFIG; then
      echo "Configuration Deleted"
    fi

    ;;

  *)
    echo "postrm called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

#DEBHELPER#

exit 0
