#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

CONFIG="/config/services/docker"

case "$1" in
    remove)
        ;;

    purge)
        logger -t DOCKER-OMV Stopping Docker service
        DOCKERSERVICE=`ps aux | grep "/usr/bin/docker daemon" | grep -v grep | wc -l`

        while [ $DOCKERSERVICE -gt 0 ]; do
            logger -t DOCKER-OMV Waiting for Docker service to stop
            service docker stop
            sleep 1
            DOCKERSERVICE=`ps aux | grep "/usr/bin/docker daemon" | grep -v grep | wc -l`
        done
        logger -t DOCKER-OMV Docker service stopped
        sed -i '/### Do not change these lines\. They are added and updated by the OMV Docker GUI plugin\./,$d' /etc/crontab
        service docker start

        if omv_config_exists $CONFIG; then
            echo "Deleting Configuration"
            omv_config_delete $CONFIG;
        fi

        if ! omv_config_exists $CONFIG; then
            echo "Configuration Deleted"
        fi
        ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

exit 0
