#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions


case "$1" in
  configure)
    
	if ! omv_config_exists "/config/services/docker"; then
      echo "Initialize configuration"
	  object="<apiPort>42005</apiPort>"
	  object="${object}<sharedfolderref></sharedfolderref>"
	  object="${object}<enabled>0</enabled>"
	  object="${object}<dockermntent></dockermntent>"
      omv_config_add_element "/config/services" "docker" "${object}" true
    fi

    dpkg-trigger update-fixperms
    dpkg-trigger update-locale

    ;;

  abort-upgrade|abort-remove|abort-deconfigure)
    ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

#DEBHELPER#

exit 0
